# Generated by Django 2.1.7 on 2019-02-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario_de_Atendimento_Integral_PAI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.CharField(max_length=10, verbose_name='Nº de registro')),
                ('data_de_registro', models.DateTimeField()),
                ('nome', models.TextField(verbose_name='Nome')),
                ('Data_de_Nascimento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('Idade', models.CharField(max_length=2)),
                ('Estado_Civil', models.TextField(verbose_name='Estado Civil')),
                ('Nome_da_Mae', models.TextField(verbose_name='Nome da Mãe')),
                ('Nome_do_Pai', models.TextField(verbose_name='Nome do Pai')),
                ('Profissao', models.TextField(verbose_name='Profissão')),
                ('Naturalidade', models.TextField(verbose_name='Naturalidade')),
                ('Endereco', models.TextField(verbose_name='Endereço')),
                ('N', models.IntegerField()),
                ('Bairro', models.CharField(max_length=32, verbose_name='Bairro')),
                ('Cidade', models.CharField(max_length=32, verbose_name='Cidade')),
                ('UF', models.TextField()),
                ('CEP', models.CharField(max_length=8)),
                ('Etnia', models.TextField()),
                ('Sexo', models.TextField()),
                ('RG', models.CharField(max_length=11)),
                ('CPF', models.CharField(max_length=11)),
                ('Cel', models.CharField(max_length=11)),
                ('Fixo', models.CharField(max_length=11)),
                ('Email', models.TextField(verbose_name='E-mail')),
            ],
        ),
    ]
