# Generated by Django 2.1.7 on 2019-03-11 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('napi', '0002_auto_20190224_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanhamento_de_Pressao_Arterial_Glicemia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('data_de_solicitacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('dia', models.DateTimeField(blank=True, null=True)),
                ('turno', models.CharField(max_length=20)),
                ('hora', models.DateTimeField(blank=True, null=True)),
                ('pa', models.CharField(blank=True, max_length=20, null=True, verbose_name='PA')),
                ('dx', models.CharField(blank=True, max_length=20, null=True, verbose_name='Dx')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requisicao_Exame_Citopatologico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pai', models.CharField(max_length=10)),
                ('nome_completo', models.CharField(max_length=200)),
                ('Nome_da_Mae', models.TextField(verbose_name='Nome da Mãe')),
                ('Data_de_Nascimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('Idade', models.IntegerField(verbose_name='Idade')),
                ('Rua', models.CharField(max_length=200, verbose_name='Endereço')),
                ('No', models.IntegerField(verbose_name='Nº')),
                ('Bairro', models.CharField(max_length=200, verbose_name='Bairro')),
                ('Cidade', models.CharField(max_length=200, verbose_name='Cidade')),
                ('Cel', models.IntegerField(verbose_name='Celular')),
                ('RG', models.IntegerField(verbose_name='RG')),
                ('CPF', models.IntegerField(verbose_name='CPF')),
                ('Usa_hormonios', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=3)),
                ('Rastreamento', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=3)),
                ('Repeticao', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=3)),
                ('Seguimento', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=3)),
                ('Ultima_vez_que_papanicolau', models.TextField()),
                ('Usa_anticoncep', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=3)),
                ('Usa_Diu', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=3)),
                ('Esta_gravida', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=3)),
            ],
        ),
    ]
