# Generated by Django 2.1.7 on 2019-03-11 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('napi', '0003_acompanhamento_de_pressao_arterial_glicemia_requisicao_exame_citopatologico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimento_terapeutico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='prontuario_de_atendimento_integral_pai',
            name='Email',
            field=models.CharField(max_length=255, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='prontuario_de_atendimento_integral_pai',
            name='Etnia',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='prontuario_de_atendimento_integral_pai',
            name='Naturalidade',
            field=models.CharField(max_length=32, verbose_name='Naturalidade'),
        ),
        migrations.AlterField(
            model_name='prontuario_de_atendimento_integral_pai',
            name='Nome_do_Pai',
            field=models.CharField(max_length=64, verbose_name='Nome do Pai'),
        ),
        migrations.AlterField(
            model_name='prontuario_de_atendimento_integral_pai',
            name='Profissao',
            field=models.CharField(max_length=32, verbose_name='Profissão'),
        ),
        migrations.AlterField(
            model_name='prontuario_de_atendimento_integral_pai',
            name='Sexo',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='prontuario_de_atendimento_integral_pai',
            name='UF',
            field=models.CharField(max_length=32),
        ),
        migrations.AddField(
            model_name='seguimento_terapeutico',
            name='numero_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='napi.Prontuario_de_Atendimento_Integral_PAI'),
        ),
    ]
