# Generated by Django 2.1.7 on 2019-03-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('napi', '0004_auto_20190311_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='ava_clinica_med_sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('tipo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('pa', models.CharField(max_length=32, verbose_name='PA')),
                ('dx', models.CharField(max_length=32, verbose_name='DX')),
                ('fr', models.CharField(max_length=32, verbose_name='FR')),
                ('pulso', models.CharField(max_length=32, verbose_name='Pulso')),
                ('sinais_sintomas', models.TextField(verbose_name='Sinais e sintomas')),
                ('alergias', models.TextField(verbose_name='Alergias')),
                ('medicacoes', models.TextField(verbose_name='Medicações')),
                ('patologias', models.TextField(verbose_name='Patologias')),
                ('liquidos', models.TextField(verbose_name='Líquidos')),
                ('alimentacao', models.TextField(verbose_name='Alimentação')),
                ('elementos_relacionados', models.TextField(verbose_name='Elementos relacionados  (Alcool e outras drogas) ')),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('profissional', models.TextField(verbose_name='Profissional')),
            ],
        ),
    ]
