# Generated by Django 2.1.7 on 2019-03-11 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('napi', '0005_ava_clinica_med_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao_exame_citopatologico',
            name='Data_de_Nascimento',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='requisicao_exame_citopatologico',
            name='Nome_da_Mae',
            field=models.CharField(max_length=255, verbose_name='Nome da Mãe'),
        ),
    ]
