# Generated by Django 2.1.7 on 2019-03-11 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('napi', '0006_auto_20190311_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao_exame_citopatologico',
            name='num_pai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='napi.Prontuario_de_Atendimento_Integral_PAI'),
        ),
    ]
