# Generated by Django 2.1.7 on 2019-03-11 13:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('napi', '0007_auto_20190311_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acomp_farmacoterapico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ini_acomp', models.DateTimeField(default=datetime.datetime(2019, 3, 11, 13, 52, 26, 649158, tzinfo=utc))),
                ('alergias', models.BooleanField()),
                ('alergias_affirm', models.CharField(blank=True, choices=[('Nega', 'Nega'), ('Sim', 'Sim'), ('Não sabe informar', 'Não sabe informar')], max_length=255, null=True, verbose_name='Alergias')),
                ('num_pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='napi.Prontuario_de_Atendimento_Integral_PAI')),
            ],
        ),
    ]
