# Generated by Django 2.1.7 on 2019-03-11 13:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('napi', '0008_acomp_farmacoterapico'),
    ]

    operations = [
        migrations.AddField(
            model_name='acomp_farmacoterapico',
            name='diabetes',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Diabetes'),
        ),
        migrations.AddField(
            model_name='acomp_farmacoterapico',
            name='hipertensao',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Hipertensão'),
        ),
        migrations.AddField(
            model_name='acomp_farmacoterapico',
            name='motivacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo da busca por atendimento'),
        ),
        migrations.AddField(
            model_name='acomp_farmacoterapico',
            name='outros',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Outros'),
        ),
        migrations.AddField(
            model_name='acomp_farmacoterapico',
            name='problema_de_saude',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da busca por atendimento'),
        ),
        migrations.AlterField(
            model_name='acomp_farmacoterapico',
            name='data_ini_acomp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 11, 13, 57, 9, 205207, tzinfo=utc)),
        ),
    ]
