# Generated by Django 2.1.7 on 2019-03-11 14:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('napi', '0009_auto_20190311_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acomp_farmacoterapico',
            name='alergias',
        ),
        migrations.AddField(
            model_name='acompanhamento_de_pressao_arterial_glicemia',
            name='num_pai',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='napi.Prontuario_de_Atendimento_Integral_PAI'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acomp_farmacoterapico',
            name='data_ini_acomp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 11, 14, 6, 24, 634777, tzinfo=utc)),
        ),
    ]
