# Generated by Django 2.1.7 on 2019-03-11 14:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('napi', '0010_auto_20190311_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha_ava_fisio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ini_acomp', models.DateField(default=datetime.datetime(2019, 3, 11, 14, 13, 19, 851940, tzinfo=utc))),
                ('hda', models.TextField(blank=True, null=True, verbose_name='HDA')),
                ('hp', models.TextField(blank=True, null=True, verbose_name='HP')),
                ('inspecao', models.TextField(blank=True, null=True, verbose_name='Inspeção')),
                ('palpacao', models.TextField(blank=True, null=True, verbose_name='Palpação')),
                ('adm', models.TextField(blank=True, null=True, verbose_name='ADM')),
                ('ava_func', models.TextField(blank=True, null=True, verbose_name='Capacidades funcionais')),
                ('asp_sens_cogn', models.TextField(blank=True, null=True, verbose_name='Aspectos sensoriais e cognitivos')),
                ('lim_func', models.TextField(blank=True, null=True, verbose_name='Limitações funcionais')),
                ('marcad_func', models.TextField(blank=True, null=True, verbose_name='Marcador funcional')),
                ('num_pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='napi.Prontuario_de_Atendimento_Integral_PAI')),
            ],
        ),
        migrations.AlterField(
            model_name='acomp_farmacoterapico',
            name='data_ini_acomp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 11, 14, 13, 19, 849937, tzinfo=utc)),
        ),
    ]
