# Generated by Django 2.1.7 on 2019-03-11 18:57

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('napi', '0011_auto_20190311_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao_exame_citopatologico',
            name='alterado',
            field=models.BooleanField(default=False, verbose_name='Alterado?'),
        ),
        migrations.AddField(
            model_name='requisicao_exame_citopatologico',
            name='anomalia_congen',
            field=models.BooleanField(default=False, verbose_name='Ausente anomalias congenitas ou retirada cirurgica'),
        ),
        migrations.AddField(
            model_name='requisicao_exame_citopatologico',
            name='data',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='requisicao_exame_citopatologico',
            name='nao_visualizado',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Colo não visualizado'),
        ),
        migrations.AddField(
            model_name='requisicao_exame_citopatologico',
            name='normal',
            field=models.BooleanField(default=False, verbose_name='Colo normal?'),
        ),
        migrations.AddField(
            model_name='requisicao_exame_citopatologico',
            name='sangramento_pos_relacao',
            field=models.BooleanField(default=False, verbose_name='Tem ou teve sangramento após relação?'),
        ),
        migrations.AddField(
            model_name='requisicao_exame_citopatologico',
            name='ultima_menstruacao',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Última menstruação'),
        ),
        migrations.AlterField(
            model_name='acomp_farmacoterapico',
            name='data_ini_acomp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ficha_ava_fisio',
            name='data_ini_acomp',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 3, 11, 18, 57, 6, 732658, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='requisicao_exame_citopatologico',
            name='Esta_gravida',
            field=models.BooleanField(default=False, verbose_name='Está grávida?'),
        ),
        migrations.AlterField(
            model_name='requisicao_exame_citopatologico',
            name='Usa_Diu',
            field=models.BooleanField(default=False, verbose_name='Usa Diu?'),
        ),
        migrations.AlterField(
            model_name='requisicao_exame_citopatologico',
            name='Usa_anticoncep',
            field=models.BooleanField(default=False, verbose_name='Usa anticoncepcional?'),
        ),
        migrations.AlterField(
            model_name='requisicao_exame_citopatologico',
            name='Usa_hormonios',
            field=models.BooleanField(default=False, verbose_name='Usa hormônio?'),
        ),
    ]
