# Generated by Django 2.1.7 on 2019-03-11 19:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('napi', '0012_auto_20190311_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Param_laborais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exame', models.CharField(max_length=64, verbose_name='Exames')),
                ('valor_de_referencia', models.CharField(max_length=64, verbose_name='Valores de referencia')),
                ('data1', models.DateField(blank=True, null=True)),
                ('data2', models.DateField(blank=True, null=True)),
                ('data3', models.DateField(blank=True, null=True)),
                ('data4', models.DateField(blank=True, null=True)),
                ('data5', models.DateField(blank=True, null=True)),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='napi.Acomp_farmacoterapico')),
            ],
        ),
        migrations.AlterField(
            model_name='ficha_ava_fisio',
            name='data_ini_acomp',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
