# Generated by Django 2.1.7 on 2019-03-11 19:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('napi', '0013_auto_20190311_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrevista_farmaceutica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Medicamento')),
                ('ps_que_trata', models.CharField(blank=True, max_length=255, null=True, verbose_name='PS que trata')),
                ('subs_ativa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Substancia ativa')),
                ('posologia_usada', models.CharField(blank=True, max_length=255, null=True, verbose_name='Posologia usada')),
                ('prescritor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prescritor')),
                ('data_ultima_prescricao', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('percepcao_da_efetividade', models.TextField(verbose_name='Percepção da efetividade')),
                ('percepcao_da_seguridade', models.TextField(verbose_name='Percepção da seguridade')),
                ('data_do_ini', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data de início')),
                ('data_do_fim', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data do fim')),
                ('modo_de_uso', models.CharField(blank=True, max_length=255, null=True, verbose_name='Modo de uso e de administração')),
                ('observacoes', models.TextField(verbose_name='Observações')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='napi.Acomp_farmacoterapico')),
            ],
        ),
    ]
