# Generated by Django 2.1.7 on 2019-02-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='idade',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
